export default {
	timezones: [
		{ val: '', label: 'default (Prague)'},
		{ val: 'Pacific/Kwajalein', label: '(GMT-12:00) International Date Line West' },
		{ val: 'Pacific/Midway', label: '(GMT-11:00) Midway Island' },
		{ val: 'Pacific/Apia', label: '(GMT-11:00) Samoa' },
		{ val: 'Pacific/Honolulu', label: '(GMT-10:00) Hawaii' },
		{ val: 'America/Anchorage', label: '(GMT-09:00) Alaska' },
		{ val: 'America/Los_Angeles', label: '(GMT-08:00) Pacific Time (US & Canada)' },
		{ val: 'America/Tijuana', label: '(GMT-08:00) Tijuana' },
		{ val: 'America/Phoenix', label: '(GMT-07:00) Arizona' },
		{ val: 'America/Denver', label: '(GMT-07:00) Mountain Time (US & Canada)' },
		{ val: 'America/Chihuahua', label: '(GMT-07:00) Chihuahua' },
		{ val: 'America/Chihuahua', label: '(GMT-07:00) La Paz' },
		{ val: 'America/Mazatlan', label: '(GMT-07:00) Mazatlan' },
		{ val: 'America/Chicago', label: '(GMT-06:00) Central Time (US & Canada)' },
		{ val: 'America/Managua', label: '(GMT-06:00) Central America' },
		{ val: 'America/Mexico_City', label: '(GMT-06:00) Guadalajara' },
		{ val: 'America/Mexico_City', label: '(GMT-06:00) Mexico City' },
		{ val: 'America/Monterrey', label: '(GMT-06:00) Monterrey' },
		{ val: 'America/Regina', label: '(GMT-06:00) Saskatchewan' },
		{ val: 'America/New_York', label: '(GMT-05:00) Eastern Time (US & Canada)' },
		{ val: 'America/Indiana/Indianapolis', label: '(GMT-05:00) Indiana (East)' },
		{ val: 'America/Bogota', label: '(GMT-05:00) Bogota' },
		{ val: 'America/Lima', label: '(GMT-05:00) Lima' },
		{ val: 'America/Bogota', label: '(GMT-05:00) Quito' },
		{ val: 'America/Halifax', label: '(GMT-04:00) Atlantic Time (Canada)' },
		{ val: 'America/Caracas', label: '(GMT-04:00) Caracas' },
		{ val: 'America/La_Paz', label: '(GMT-04:00) La Paz' },
		{ val: 'America/Santiago', label: '(GMT-04:00) Santiago' },
		{ val: 'America/St_Johns', label: '(GMT-03:30) Newfoundland' },
		{ val: 'America/Sao_Paulo', label: '(GMT-03:00) Brasilia' },
		{ val: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Buenos Aires' },
		{ val: 'America/Argentina/Buenos_Aires', label: '(GMT-03:00) Georgetown' },
		{ val: 'America/Godthab', label: '(GMT-03:00) Greenland' },
		{ val: 'America/Noronha', label: '(GMT-02:00) Mid-Atlantic' },
		{ val: 'Atlantic/Azores', label: '(GMT-01:00) Azores' },
		{ val: 'Atlantic/Cape_Verde', label: '(GMT-01:00) Cape Verde Is.' },
		{ val: 'Africa/Casablanca', label: '(GMT) Casablanca' },
		{ val: 'Europe/London', label: '(GMT) Dublin' },
		{ val: 'Europe/London', label: '(GMT) Edinburgh' },
		{ val: 'Europe/Lisbon', label: '(GMT) Lisbon' },
		{ val: 'Europe/London', label: '(GMT) London' },
		{ val: 'Africa/Monrovia', label: '(GMT) Monrovia' },
		{ val: 'Europe/Amsterdam', label: '(GMT+01:00) Amsterdam' },
		{ val: 'Europe/Belgrade', label: '(GMT+01:00) Belgrade' },
		{ val: 'Europe/Berlin', label: '(GMT+01:00) Berlin' },
		{ val: 'Europe/Berlin', label: '(GMT+01:00) Bern' },
		{ val: 'Europe/Bratislava', label: '(GMT+01:00) Bratislava' },
		{ val: 'Europe/Brussels', label: '(GMT+01:00) Brussels' },
		{ val: 'Europe/Budapest', label: '(GMT+01:00) Budapest' },
		{ val: 'Europe/Copenhagen', label: '(GMT+01:00) Copenhagen' },
		{ val: 'Europe/Ljubljana', label: '(GMT+01:00) Ljubljana' },
		{ val: 'Europe/Madrid', label: '(GMT+01:00) Madrid' },
		{ val: 'Europe/Paris', label: '(GMT+01:00) Paris' },
		{ val: 'Europe/Prague', label: '(GMT+01:00) Prague' },
		{ val: 'Europe/Rome', label: '(GMT+01:00) Rome' },
		{ val: 'Europe/Sarajevo', label: '(GMT+01:00) Sarajevo' },
		{ val: 'Europe/Skopje', label: '(GMT+01:00) Skopje' },
		{ val: 'Europe/Stockholm', label: '(GMT+01:00) Stockholm' },
		{ val: 'Europe/Vienna', label: '(GMT+01:00) Vienna' },
		{ val: 'Europe/Warsaw', label: '(GMT+01:00) Warsaw' },
		{ val: 'Africa/Lagos', label: '(GMT+01:00) West Central Africa' },
		{ val: 'Europe/Zagreb', label: '(GMT+01:00) Zagreb' },
		{ val: 'Europe/Athens', label: '(GMT+02:00) Athens' },
		{ val: 'Europe/Bucharest', label: '(GMT+02:00) Bucharest' },
		{ val: 'Africa/Cairo', label: '(GMT+02:00) Cairo' },
		{ val: 'Africa/Harare', label: '(GMT+02:00) Harare' },
		{ val: 'Europe/Helsinki', label: '(GMT+02:00) Helsinki' },
		{ val: 'Europe/Istanbul', label: '(GMT+02:00) Istanbul' },
		{ val: 'Asia/Jerusalem', label: '(GMT+02:00) Jerusalem' },
		{ val: 'Europe/Kiev', label: '(GMT+02:00) Kyev' },
		{ val: 'Europe/Minsk', label: '(GMT+02:00) Minsk' },
		{ val: 'Africa/Johannesburg', label: '(GMT+02:00) Pretoria' },
		{ val: 'Europe/Riga', label: '(GMT+02:00) Riga' },
		{ val: 'Europe/Sofia', label: '(GMT+02:00) Sofia' },
		{ val: 'Europe/Tallinn', label: '(GMT+02:00) Tallinn' },
		{ val: 'Europe/Vilnius', label: '(GMT+02:00) Vilnius' },
		{ val: 'Asia/Baghdad', label: '(GMT+03:00) Baghdad' },
		{ val: 'Asia/Kuwait', label: '(GMT+03:00) Kuwait' },
		{ val: 'Europe/Moscow', label: '(GMT+03:00) Moscow' },
		{ val: 'Africa/Nairobi', label: '(GMT+03:00) Nairobi' },
		{ val: 'Asia/Riyadh', label: '(GMT+03:00) Riyadh' },
		{ val: 'Europe/Moscow', label: '(GMT+03:00) St. Petersburg' },
		{ val: 'Europe/Volgograd', label: '(GMT+03:00) Volgograd' },
		{ val: 'Asia/Tehran', label: '(GMT+03:30) Tehran' },
		{ val: 'Asia/Muscat', label: '(GMT+04:00) Abu Dhabi' },
		{ val: 'Asia/Baku', label: '(GMT+04:00) Baku' },
		{ val: 'Asia/Muscat', label: '(GMT+04:00) Muscat' },
		{ val: 'Asia/Tbilisi', label: '(GMT+04:00) Tbilisi' },
		{ val: 'Asia/Yerevan', label: '(GMT+04:00) Yerevan' },
		{ val: 'Asia/Kabul', label: '(GMT+04:30) Kabul' },
		{ val: 'Asia/Yekaterinburg', label: '(GMT+05:00) Ekaterinburg' },
		{ val: 'Asia/Karachi', label: '(GMT+05:00) Islamabad' },
		{ val: 'Asia/Karachi', label: '(GMT+05:00) Karachi' },
		{ val: 'Asia/Tashkent', label: '(GMT+05:00) Tashkent' },
		{ val: 'Asia/Kolkata', label: '(GMT+05:30) Chennai' },
		{ val: 'Asia/Kolkata', label: '(GMT+05:30) Kolkata' },
		{ val: 'Asia/Kolkata', label: '(GMT+05:30) Mumbai' },
		{ val: 'Asia/Kolkata', label: '(GMT+05:30) New Delhi' },
		{ val: 'Asia/Kathmandu', label: '(GMT+05:45) Kathmandu' },
		{ val: 'Asia/Almaty', label: '(GMT+06:00) Almaty' },
		{ val: 'Asia/Dhaka', label: '(GMT+06:00) Astana' },
		{ val: 'Asia/Dhaka', label: '(GMT+06:00) Dhaka' },
		{ val: 'Asia/Novosibirsk', label: '(GMT+06:00) Novosibirsk' },
		{ val: 'Asia/Colombo', label: '(GMT+06:00) Sri Jayawardenepura' },
		{ val: 'Asia/Rangoon', label: '(GMT+06:30) Rangoon' },
		{ val: 'Asia/Bangkok', label: '(GMT+07:00) Bangkok' },
		{ val: 'Asia/Bangkok', label: '(GMT+07:00) Hanoi' },
		{ val: 'Asia/Jakarta', label: '(GMT+07:00) Jakarta' },
		{ val: 'Asia/Krasnoyarsk', label: '(GMT+07:00) Krasnoyarsk' },
		{ val: 'Asia/Hong_Kong', label: '(GMT+08:00) Beijing' },
		{ val: 'Asia/Chongqing', label: '(GMT+08:00) Chongqing' },
		{ val: 'Asia/Hong_Kong', label: '(GMT+08:00) Hong Kong' },
		{ val: 'Asia/Irkutsk', label: '(GMT+08:00) Irkutsk' },
		{ val: 'Asia/Kuala_Lumpur', label: '(GMT+08:00) Kuala Lumpur' },
		{ val: 'Australia/Perth', label: '(GMT+08:00) Perth' },
		{ val: 'Asia/Singapore', label: '(GMT+08:00) Singapore' },
		{ val: 'Asia/Taipei', label: '(GMT+08:00) Taipei' },
		{ val: 'Asia/Irkutsk', label: '(GMT+08:00) Ulaan Bataar' },
		{ val: 'Asia/Urumqi', label: '(GMT+08:00) Urumqi' },
		{ val: 'Asia/Tokyo', label: '(GMT+09:00) Osaka' },
		{ val: 'Asia/Tokyo', label: '(GMT+09:00) Sapporo' },
		{ val: 'Asia/Seoul', label: '(GMT+09:00) Seoul' },
		{ val: 'Asia/Tokyo', label: '(GMT+09:00) Tokyo' },
		{ val: 'Asia/Yakutsk', label: '(GMT+09:00) Yakutsk' },
		{ val: 'Australia/Adelaide', label: '(GMT+09:30) Adelaide' },
		{ val: 'Australia/Darwin', label: '(GMT+09:30) Darwin' },
		{ val: 'Australia/Brisbane', label: '(GMT+10:00) Brisbane' },
		{ val: 'Australia/Sydney', label: '(GMT+10:00) Canberra' },
		{ val: 'Pacific/Guam', label: '(GMT+10:00) Guam' },
		{ val: 'Australia/Hobart', label: '(GMT+10:00) Hobart' },
		{ val: 'Australia/Melbourne', label: '(GMT+10:00) Melbourne' },
		{ val: 'Pacific/Port_Moresby', label: '(GMT+10:00) Port Moresby' },
		{ val: 'Australia/Sydney', label: '(GMT+10:00) Sydney' },
		{ val: 'Asia/Vladivostok', label: '(GMT+10:00) Vladivostok' },
		{ val: 'Asia/Magadan', label: '(GMT+11:00) Magadan' },
		{ val: 'Asia/Magadan', label: '(GMT+11:00) New Caledonia' },
		{ val: 'Asia/Magadan', label: '(GMT+11:00) Solomon Is.' },
		{ val: 'Pacific/Auckland', label: '(GMT+12:00) Auckland' },
		{ val: 'Pacific/Fiji', label: '(GMT+12:00) Fiji' },
		{ val: 'Asia/Kamchatka', label: '(GMT+12:00) Kamchatka' },
		{ val: 'Pacific/Fiji', label: '(GMT+12:00) Marshall Is.' },
		{ val: 'Pacific/Auckland', label: '(GMT+12:00) Wellington' },
		{ val: 'Pacific/Tongatapu', label: '(GMT+13:00) Nuku alofa' }
	]
}